[package]
name = "pokenotifications"
version = "0.1.0"
authors = ["Gonzalo Busto Musi <gonzalo.busto@gmail.com"]
edition = '2021'

[dependencies]
scraper = "0.19.0"
reqwest = "0.12.4"
tokio = { version = "1", features = ["full"] }
regex = "1.10.4"